### ISSUE TITLE
Missing name_map.json file

### ISSUE THREAD

**Issue by mann1** [Zoeyyao27/Graph-of-Thought#1]
Thank you for the great work. When I tried to reproduce the results on ScienceQA, I found that the name_map.json is missing from their repo. Do you happen to have a copy available?

**Comment by Zoeyyao27** [comment]
You can find name_map.json here [https://github.com/amazon-science/mm-cot/blob/main/data/name_map.json](https://github.com/amazon-science/mm-cot/blob/main/data/name_map.json). Also I have uploaded the file in the ScienceQA floder.
